# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Envoy Proxy

description: > # this means to ignore newlines until "baseurl:"
  Envoy is an open source edge and service proxy, designed for cloud-native applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.envoyproxy.io"

latest: 1.23.0

sass:
  style: compressed

# Build settings
markdown: kramdown
# plugins:
#  - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Google Analytics
google_analytics: UA-148359966-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- bazel
- site
- node_modules
- vendor

include:
- _static
