# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Envoy Proxy

description: > # this means to ignore newlines until "baseurl:"
  Envoy is an open source edge and service proxy, designed for cloud-native applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://envoyproxy.github.io" # the base hostname & protocol for your site, e.g. http://example.com

latest: 1.16.2

versions:
- 1.16.2
- 1.16.1
- 1.16.0
- 1.15.3
- 1.15.2
- 1.15.0
- 1.14.6
- 1.14.5
- 1.14.4
- 1.14.3
- 1.14.2
- 1.14.1
- 1.14.0
- 1.13.7
- 1.13.6
- 1.13.5
- 1.13.4
- 1.13.3
- 1.13.2
- 1.13.1
- 1.13.0
- 1.12.7
- 1.12.6
- 1.12.5
- 1.12.4
- 1.12.3
- 1.12.2
- 1.12.1
- 1.12.0
- 1.11.2
- 1.11.1
- 1.11.0
- 1.10.0
- 1.9.1
- 1.9.0
- 1.8.0
- 1.7.1
- 1.7.0
- 1.6.0
- 1.5.0

sass:
  style: compressed

# Build settings
markdown: kramdown
# plugins:
#  - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Google Analytics
google_analytics: UA-148359966-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - docs/
  - vendor
